spring.application.name=Login

server.port=8081
server.servlet.context-path=/api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=THIS_IS_SUPER_SECRET_KEY_FOR_JWT_AUTH_SYSTEM_123456789
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${DB_GMAIL}
spring.mail.password=${DB_GMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true